# Generated by Django 6.1 on 2026-08-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('nationality', models.CharField(default='Nepali', max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('previous_school', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('father_contact', models.CharField(max_length=20)),
                ('mother_contact', models.CharField(max_length=20)),
                ('guardian_contact', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward_no', models.CharField(max_length=10)),
                ('tole_village', models.CharField(max_length=100)),
                ('permanent_address', models.TextField()),
                ('temporary_address', models.TextField()),
                ('applying_for', models.CharField(max_length=50)),
                ('previous_class', models.CharField(max_length=50)),
                ('previous_school_address', models.TextField()),
                ('previous_gpa_percentage', models.CharField(max_length=20)),
                ('student_photo', models.ImageField(upload_to='admission/student_photos/')),
                ('birth_certificate', models.FileField(upload_to='admission/birth_certificates/')),
                ('previous_school_certificate', models.FileField(upload_to='admission/school_certificates/')),
                ('medical_information', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
